### ISSUE TITLE
No seen on IG messages

### ISSUE THREAD

**Issue by carneeki** [diessica/no-seen#3]
I've noticed during messaging on IG, the browser will POST to `https://i.instagram.com/api/v1/direct_v2/threads/<userid>/items/<conversationid>/seen/`

I think the following regex might be a solution to blocking seen status for IG messages:

`'*://*.instagram.com/api/v1/direct_v2/threads/*/items/*/seen/'`

**Comment by carneeki** [comment]
Regex appears to block seen on message.

**Comment by carneeki** [comment]
I will likely need to modify the regex, in the last few days it has stopped working. I suspect it might be because I enabled cross-platform messaging between IG and FB.

**Comment by diessica** [comment]
closed in favour of #4
