### ISSUE TITLE
New URL for IG stories

### ISSUE THREAD

**Issue by carneeki** [diessica/no-seen#4]
The URL for IG stories has changed in the last few days.

Suggest adding:
`'*://*.instagram.com/api/v1/stories/reel/seen',`
to `URLS_TO_CANCEL`.

My `URLS_TO_CANCEL` is now as follows and includes blocking the seen status for IG messages.

```javascript
const URLS_TO_CANCEL = [
	'*://*.facebook.com/ajax/mercury/change_read_status.php*',
	'*://*.instagram.com/ajax/bz*',
	'*://*.instagram.com/qp/batch_fetch_web*',
	'*://*.instagram.com/api/v1/stories/reel/seen',
	'*://*.instagram.com/api/v1/direct_v2/threads/*/items/*/seen/',
]
```

**Comment by kenarsene** [comment]
> The URL for IG stories has changed in the last few days.
> 
> Suggest adding: `'*://*.instagram.com/api/v1/stories/reel/seen',` to `URLS_TO_CANCEL`.
> 
> My `URLS_TO_CANCEL` is now as follows and includes blocking the seen status for IG messages.
> 
> ```js
> const URLS_TO_CANCEL = [
> 	'*://*.facebook.com/ajax/mercury/change_read_status.php*',
> 	'*://*.instagram.com/ajax/bz*',
> 	'*://*.instagram.com/qp/batch_fetch_web*',
> 	'*://*.instagram.com/api/v1/stories/reel/seen',
> 	'*://*.instagram.com/api/v1/direct_v2/threads/*/items/*/seen/',
> ]
> ```

Hi I was using your new urls but it seem to stop working as of this moment, did they change the urls again if so can you post the updated urls. thanks.

**Comment by ni-dgurskas** [comment]
Thanks @carneeki. I will update it!

**Comment by diessica** [comment]
Thanks @carneeki. I will release a new version.
