### ISSUE TITLE
Addon doesn't work anymore

### ISSUE THREAD

**Issue by Dyras** [diessica/no-seen#5]
Hello! Thanks for making seemingly the only functioning Facebook unseen addon for Firefox at the moment!

However, it doesn't seem to work for messenger.com. Any chance you could add support for that?

Edit: In fact, it doesn't seem to be working on Facebook either for that matter.

**Comment by charichard08** [comment]
Is this extension still maintained? I remember using it a year ago and it used to work. Now it doesn't?

**Comment by diessica** [comment]
please see https://github.com/diessica/no-seen/issues/7#issuecomment-2389106201
